Repository chrislopresto/ember-freestyle, pull requests merged in 2023-07, with the labels that each got.

#928 Fix compatibility with `ember-cli` v5
  .github/workflows/ci.yml
  index.js
  package.json
  yarn.lock
Labels: bug

#929 Support `ember-modifier` v4
  package.json
  yarn.lock
Labels: enhancement

#950 Update versions of ember-qunit and ember-test-helpers
  config/ember-try.js
  package.json
  yarn.lock
Labels: internal
