Repository chrislopresto/ember-freestyle, pull requests merged in 2023-09, with the labels that each got.

#963 Add an Api type to Freestyle::Usage for when you expect a component as argument
  addon/components/freestyle/usage/component-like/control/index.hbs
  addon/components/freestyle/usage/component-like/control/index.ts
  addon/components/freestyle/usage/component-like/index.hbs
  addon/components/freestyle/usage/component-like/index.ts
  addon/components/freestyle/usage/index.hbs
  addon/components/freestyle/usage/index.ts
  addon/glint.ts
  app/components/freestyle/usage/component-like.js
  app/components/freestyle/usage/component-like/control.js
  package.json
  tests/dummy/app/components/markdown-content/index.ts
  tests/integration/components/freestyle/usage/component-like-test.ts
  yarn.lock
Labels: enhancement

#957 Add `@ember/string` as a peer dependency
  package.json
Labels: bug, breaking

#964 Update prettier
  addon/components/freestyle-collection/index.ts
  addon/components/freestyle-dynamic/index.ts
  addon/components/freestyle-palette/index.ts
  addon/components/freestyle-section/index.ts
  addon/components/freestyle-source/index.ts
  addon/components/freestyle-subsection/index.ts
  addon/components/freestyle/usage/index.ts
  addon/decorators/css-variable.ts
  addon/utils/css-rules.ts
  app/styles/components/freestyle-collection.scss
  app/styles/components/freestyle-guide.scss
  app/styles/components/freestyle-usage-controls.scss
  lib/ast-transform.js
  package.json
  tests/acceptance/dynamic-test.ts
  tests/acceptance/section-navigation-test.ts
  tests/acceptance/section-rendering-test.ts
  tests/dummy/app/components/progress-icon/index.ts
  tests/helpers/index.ts
  tests/integration/components/freestyle-guide/component-test.ts
  tests/integration/components/freestyle-palette/component-test.ts
  tests/integration/components/freestyle-usage/component-test.ts
  tests/integration/components/freestyle/usage-test.ts
  tests/integration/components/freestyle/usage/component-like-test.ts
  types/ember-truth-helpers/helpers/and.d.ts
  types/ember-truth-helpers/helpers/or.d.ts
  yarn.lock
Labels: chore

#965 Update glint and add glint to CI
  package.json
  tests/dummy/app/components/album-cover/index.hbs
  tests/dummy/app/components/markdown-content/index.hbs
  tests/dummy/app/components/markdown-content/index.ts
  tests/dummy/app/components/x-foo/index.hbs
  tests/dummy/app/templates/documentation.hbs
  yarn.lock
Labels: chore
