Repository chrislopresto/ember-freestyle, pull requests merged in 2024-03, with the labels that each got.

#995 Provide an extendable template registry
  README.md
  addon/glint.ts
  addon/template-registry.ts
  tests/integration/components/freestyle/usage/component-like-test.ts
  types/global.d.ts
Labels: enhancement, breaking

#997 Fix typo in usage-test
  tests/integration/components/freestyle/usage-test.ts
Labels: greenkeeper

#998 Fix import path for `SafeString` type
  addon/components/freestyle-palette-item/index.ts
  package.json
  types/global.d.ts
  yarn.lock
Labels: bug
